[package]
name = "politiknow"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
reqwest = "0.11"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"]}
dotenv = "0.15.0"